# Generated by Django 5.2.17 on 2026-09-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('prestado', 'Prestado')], default='disponible', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('prestado_a', models.CharField(blank=True, max_length=100, verbose_name='Quién lo tiene')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
