# Generated by Django 5.2.17 on 2026-09-12 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_seed_datos'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutorizacionEspacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('vigente', 'Vigente'), ('vencida', 'Vencida'), ('revocada', 'Revocada')], default='vigente', max_length=20)),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizaciones', to='prestamos.espacio')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizaciones', to='prestamos.solicitante')),
            ],
            options={
                'verbose_name': 'autorización de espacio',
                'verbose_name_plural': 'autorizaciones de espacio',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AddField(
            model_name='solicitante',
            name='espacios',
            field=models.ManyToManyField(blank=True, related_name='solicitantes', through='prestamos.AutorizacionEspacio', to='prestamos.espacio'),
        ),
        migrations.CreateModel(
            name='PerfilSolicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_identidad', models.CharField(max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('area_o_ciclo', models.CharField(blank=True, max_length=80, verbose_name='Área o ciclo')),
                ('observaciones', models.TextField(blank=True)),
                ('solicitante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='prestamos.solicitante')),
            ],
            options={
                'verbose_name': 'perfil de solicitante',
                'verbose_name_plural': 'perfiles de solicitante',
            },
        ),
    ]
