# Generated by Django 5.2.17 on 2026-09-12 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_seed_equipos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('tipo', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionAccesorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('fecha_asignacion', models.DateField()),
                ('estado', models.CharField(choices=[('vigente', 'Vigente'), ('devuelto', 'Devuelto'), ('perdido', 'Perdido')], default='vigente', max_length=20)),
                ('accesorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='equipment.accesorio')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_accesorio', to='equipment.equipo')),
            ],
            options={
                'verbose_name': 'asignación de accesorio',
                'verbose_name_plural': 'asignaciones de accesorio',
                'ordering': ['-fecha_asignacion'],
            },
        ),
        migrations.AddField(
            model_name='accesorio',
            name='equipos',
            field=models.ManyToManyField(blank=True, related_name='accesorios', through='equipment.AsignacionAccesorio', to='equipment.equipo'),
        ),
        migrations.CreateModel(
            name='FichaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=80)),
                ('fecha_adquisicion', models.DateField(blank=True, null=True)),
                ('garantia_hasta', models.DateField(blank=True, null=True)),
                ('especificaciones', models.TextField(blank=True)),
                ('equipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha', to='equipment.equipo')),
            ],
            options={
                'verbose_name': 'ficha técnica',
                'verbose_name_plural': 'fichas técnicas',
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo')], max_length=20)),
                ('tecnico', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='equipment.equipo')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
