# Generated by Django 5.2.17 on 2026-09-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_seed_relaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesorio',
            name='existencias',
            field=models.PositiveIntegerField(default=0, help_text='Unidades en almacén. Se descuenta al asignar el accesorio a un equipo.'),
        ),
    ]
