# Generated by Django 5.2.17 on 2026-09-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0004_seed_relaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='espacio',
            name='cupos_disponibles',
            field=models.PositiveIntegerField(default=0, help_text='Autorizaciones vigentes adicionales que este espacio puede admitir. No modifica el aforo.', verbose_name='Cupos disponibles'),
        ),
    ]
